server:
	host: localhost
	port: 2004 2005 2006
	root: /Users/rarraji/Desktop/WS_BETTA/pages/web3
	max_body_size: 100
	index: index.html
	server_name: hello.com

	error_pages:
		400: ErrorPages/400.html
		401: ErrorPages/401.html
		403: ErrorPages/403.html
		405: ErrorPages/405.html
		413: ErrorPages/413.html

location: /
	upload_dir: /upload
	index: index_.html
	methods: GET POST
location: /server1/
	index: index.html
	methods: GET POST
location: /server1/web1/
	directory_listing: true
	methods: GET POST
location: /cgi/
	index: index.html
	methods: GET POST